#!/bin/sh

LXC_BRIDGE="lxcbr0"
LXC_BRIDGE_ADDR="10.0.3.1/24"
LXC_NETMASK="255.255.255.0"
LXC_NETWORK="10.0.3.0/24"

ip link add name $LXC_BRIDGE type bridge
ip link set dev $LXC_BRIDGE up
ip addr add dev $LXC_BRIDGE $LXC_BRIDGE_ADDR
